language: python
dist: trusty
matrix:
  include:
  - python: 3.7
    dist: xenial
    sudo: true
install:
  - pip install -r requirements.txt

addons:
  sonarcloud:
    organization: "juligreen-github"
    token: $SONAR_TOKEN

script:
  - sonar-scanner