= GameDeals
Doc Writer <julius.dehner@gmail.com>

== Work in progress!

== Description

Finished features:

- get current deals from r/GameDeals
- check if the game has at least 1000 ratings on steam
- compare prices with G2A

TODOs:

- message you on Telegram, when there is a certain profit margin by selling the game on G2A
- test cases
- proper logging

Features I might implement:

- creating graphs of price develpment while on sale (probably using bokeh)
- writing a message on telegram to track game sales regardless of G2A prices
- telegram interactivity https://github.com/python-telegram-bot/python-telegram-bot/wiki/Types-of-Handlers[(docs)]


== Open Source

You are free to reuse this code in other projects (so long as you distibute source code with binarys) as stated by the GPL License but I'd be very happy if you would message me at julius<dot>dehner<at>gmail<dot>com and tell me what you're using it for, just because I'm very curious :)

== Dependencies

This project uses:

- https://github.com/SeleniumHQ/selenium[Selenium]
- https://github.com/praw-dev/praw[PRAW]
- https://github.com/python-telegram-bot/python-telegram-bot[python-telegram-bot]

NOTE: This project has been set up using PyScaffold 3.0.3. For details and usage information on PyScaffold see http://pyscaffold.org/.
