= Agentibus G2A
Doc Writer <julius.dehner@gmail.com>

== Now in beta!
Preferred (and currently the only supported) installation method is docker.

=== Installation steps:

- install docker https://docs.docker.com/toolbox/overview/[Windows]|[Ubuntu]
- create telegram bot by talking to https://t.me/botfather[BotFather] and note your access token
- get your chat id by talking to @get_id_bot and using the "/my_id" command
- create configuration.ini like https://github.com/juligreen/GameDeals/blob/master/src/gamedeals/resources/configuration.ini.example[this example file]
- now start the docker container with the following command (replace path/to/folder/which/contains/configuration.ini with the folder in which you have your configuration.ini)

 docker run --name agentibus --restart unless-stopped -v path/to/folder/which/contains/configuration.ini:/home/gamedeals/resources juligreen/agentibus-g2a


=== Currently supported sites

- https://www.humblebundle.com/[HumbleBundle]
- https://www.humblebundle.com/store[Humble Store]
- https://www.fanatical.com/[Fanatical Store]

== Description

Finished features:

- check if a game has at least 1000 ratings on steam (less relevant for bundles)
- compare prices with G2A
- message you on Telegram, when there is a certain profit margin by selling the game on G2A

TODOs:

- test cases
- proper logging

Features I might implement:

- creating graphs of price develpment while on sale (probably using https://github.com/spotify/chartify[chartify] which is built on bokeh)
- writing a message on telegram to track game sales regardless of G2A prices
- telegram interactivity https://github.com/python-telegram-bot/python-telegram-bot/wiki/Types-of-Handlers[(docs)]


== Open Source

You are free to reuse this code in other projects (so long as you distibute source code with binarys) as stated by the GPL License but I'd be very happy if you would message me at julius<dot>dehner<at>gmail<dot>com and tell me what you're using it for, just because I'm very curious :)

== Trivia

Agentibus is latin for efficient :)

== Dependencies

This project uses:

- https://github.com/SeleniumHQ/selenium[Selenium]
- https://github.com/python-telegram-bot/python-telegram-bot[python-telegram-bot]
- https://github.com/dbader/schedule[Schedule] - huge thanks to Dan Bader for this awesome library and his great python books!

NOTE: This project has been set up using PyScaffold 3.0.3. For details and usage information on PyScaffold see http://pyscaffold.org/.
