= GameDeals
Doc Writer <julius.dehner@gmail.com>

== Work in progress!
The Project will probably change in that it scrapes deals directly from the deal sites instead of reddit, as this should give better performance (less regex) and better coverage.

== Description

Finished features:

- get current deals from r/GameDeals
- check if the game has at least 1000 ratings on steam
- compare prices with G2A

TODOs:

- merge multiple classes into fewer modules (python best practice)
- message you on Telegram, when there is a certain profit margin by selling the game on G2A
- test cases
- proper logging

Features I might implement:

- creating graphs of price develpment while on sale (probably using https://github.com/spotify/chartify[chartify] which is built on bokeh)
- writing a message on telegram to track game sales regardless of G2A prices
- telegram interactivity https://github.com/python-telegram-bot/python-telegram-bot/wiki/Types-of-Handlers[(docs)]


== Open Source

You are free to reuse this code in other projects (so long as you distibute source code with binarys) as stated by the GPL License but I'd be very happy if you would message me at julius<dot>dehner<at>gmail<dot>com and tell me what you're using it for, just because I'm very curious :)

== Dependencies

This project uses:

- https://github.com/SeleniumHQ/selenium[Selenium]
- https://github.com/python-telegram-bot/python-telegram-bot[python-telegram-bot]
- https://github.com/dbader/schedule[Schedule] - huge thanks to Dan Bader for this awesome library and his great python books!

NOTE: This project has been set up using PyScaffold 3.0.3. For details and usage information on PyScaffold see http://pyscaffold.org/.
